### ISSUE TITLE
Cannot assign to read only property 'isEmpty' of #<Deque>

### ISSUE THREAD

**Issue by Serboy** [petkaantonov/deque#9]
Hi Sir,
  Please help me, how can I resolve this problem?

TypeError: Cannot assign to read only property 'isEmpty' of #<Deque>
    at Object.<anonymous> (C:\Users\Acer Valued Customer\Documents\Serboy\Coding\Analytics\Analytics.Web\node_modules\double-ended-queue\js\deque.js:185:25)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Acer Valued Customer\Documents\Serboy\Coding\Analytics\Analytics.Web\node_modules\redis\index.js:8:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Acer Valued Customer\Documents\Serboy\Coding\Analytics\Analytics.Web\node_modules\connect-redis\lib\connect-redis.js:8:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Acer Valued Customer\Documents\Serboy\Coding\Analytics\Analytics.Web\node_modules\connect-redis\index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

Thanks,

**Comment by iamkdblue** [comment]
correct way to use isEmpty() not isEmpty , i hope its help you !
